# -*- coding: utf-8 -*-
"""
========================================================================================================
Module: experimental_data_postprocessing
Author: Caio Dias Filho
Creation date: 2026-04-27
Last modification: 2026-04-27
Version: 2.0 (final)
========================================================================================================

OVERVIEW
--------
This module performs the post-processing of experimental aerodynamic data acquired from wind tunnel
tests at the Laboratory of Aerodynamics (LAE) of the University of Sao Paulo (USP).

The pipeline converts raw balance and pressure-scan measurements into a structured partial dataset
containing corrected aerodynamic operating conditions and surface pressure coefficient distributions.

The outputs generated by this module correspond to subsets of the complete experimental database and 
are inteded to be merged manually with results from other sensor configurations in a later assembly 
stage.

Each processed partial dataset contains:

    - Corrected Reynold number;
    - Corrected angle of attack;
    - Spanwise position;
    - Surface pressure coefficient distribution (Cp)

This workflow includes blockage correction, lift-based angle-of-attack correction, pressure coefficient
computation, interpolation of missing taps, and export of publication-ready visual validation plots.


WORKFLOW
--------
The implemented workflow consists of:

    - Reading raw polar and scan files;
    - Mapping pressure channels to physical taps;
    - Computing dynamic pressure from reference measurements;
    - Applying wind tunnel blockage correction;
    - Computing pressure coefficients (Cp);
    - Reconstructing sectional datasets for each spanwise station;
    - Applying Reynolds number correction;
    - Computing global lift coefficient (CL);
    - Correcting angle of attack using lift interference correction;
    - Interpolating missing pressure taps;
    - Renaming Cp columns usinf chordwise coordinates;
    - Exporting processed partial datasets;
    - Generating visual inspection plots;
    - Preparing outputs for later manual dataset merging.

        
DEPENDENCIES
------------
Python libraries:

    - matplotlib
    - pahtlib
    - pandas
    - numpy

External files:

    - Raw aerodynamic polar file (.pol)
    - Raw pressure scan files (.dat)
    - Sensor mapping file (.csv)


OUTPUT FILES
------------
Processed partial datasets:

    - pipeline-output/<case_name>.csv

Visual inspection plots:

    - visual-checks/<case_name>.png


ASSUMPTIONS
-----------
The implementation assumes that: 

    - Each scan file corresponds to one operating condition.
    - The number of scans is fixed at 21.
    - Sensor mapping files correctly associate channels with pressure taps.
    - Pressure taps belong to predefined spanwise sections.
    - The wind tunnel geometry and model dimensions are constant.
    - Calibration factors for lift conversion are valid.
    - Missing pressure taps can be approximated by linear interpolation.
    - Each execution processes only one sensor configuration at a time.
    - The complete experimental dataset is assembled externally fater all configurations are individually
    processed.


LIMITATIONS
-----------
Potential limitations include:

    - Correction factors are based on simplified analytical formulations.
    - The number of scan files is hardcoded.
    - Mapping logic depends on predefined configuration names.
    - Interpolation may smooth localized pressure features.
    - Results depend directly on sensor quality and raw acquisition accuracy.
    - Final database consistency depends on the external merging procedure.

========================================================================================================
"""

# =======================================================================================================
#                                            USER INPUT SECTION
# =======================================================================================================

# --- Complete aerodynamic data file path ---
complete_aerodynamic_data_path = 'experimental-input/CompleteRun_V30_DeltaConfig.pol'

# --- Fuselage aerodynamic data file path ---
fuselage_aerodynamic_data_path = 'experimental-input/FuselageRun_V30.pol'

# --- Configuration mapping file path ---
configuration_map_path = 'sensor-mappings/Delta_Mapping.csv'


# =======================================================================================================
#                                              CORE FUNCTION
# =======================================================================================================

from matplotlib.ticker import MaxNLocator
from matplotlib import pyplot as plt
from pathlib import Path
import pandas as pd
import numpy as np

def calculate_blockage_correction(AoA_uncorrected: float):
    """
    Compute the wind tunnel blockage correction factor.

    This function estimates the blockage effect caused by the model frontal area inside the test section.
    The frontal area is evaluated as a function of the uncorrected angle of attack.

    Parameters
    ----------
    AoA_uncorrected : float
        Uncorrected angle of attack, in degrees.

    Returns
    -------
    blockage_factor : float
        Blockage correction factor used to correct the operating conditions.    
    """

    # --- LAE wind tunnel test section area in m² ---
    S_tunnel = 1.30 * 1.70

    # --- LAE 2008 Model wing geometry data in m ---
    w_chord = 0.2165
    w_span = 0.766
    w_thickness = 0.15 * w_chord

    # --- LAE 2008 Model fuselage geometry data in m ---
    f_lenght = 1.200
    f_height = 0.240
    f_width = 0.130

    # --- Calculates the model's frontal area for different angles of attack ---
    # Converts angles from degrees to radians:
    AoA_radians = np.deg2rad(AoA_uncorrected)

    # Individual contributions:
    w_frontal_area = w_span * (w_thickness * np.cos(AoA_radians) + w_chord * abs(np.sin(AoA_radians)))
    f_frontal_area = f_width * (f_height * np.cos(AoA_radians) + f_lenght * abs(np.sin(AoA_radians)))

    # Model's front area:
    model_frontal_area = w_frontal_area + f_frontal_area

    # --- Calculates the blockage correction factor ---
    blockage_factor = 0.25 * (model_frontal_area / S_tunnel)

    return blockage_factor

def process_scan_data(scan_path: str, configuration_map_path: str, section_number: int, 
    AoA_uncorrected: float):
    """
    Process one pressure scan file for a selected wing section.

    This function loads the raw scan data, maps pressure channels to physical taps, computes corrected
    dynamic pressure, evaluates pressure coefficients, and returns the processed data for one spanwise
    section.

    Parameters
    ----------
    scan_path : str
        Path to the raw pressure scan file.

    configuration_map_path : str
        Path to the sensor mapping file associated with the selected configuration.

    section_number : int
        Spanwise section identifier to be extracted.

    AoA_uncorrected : float
        Uncorrected angle of attack associated with the scan condition.

    Returns
    -------
    scan_data: pandas.DataFrame
        Single-row dataframe containing the processed pressure coefficient distribution for the selected
        wing section.
    """

    # --- Loads the scan data and configuration map dataset ---
    scan_data = pd.read_csv(scan_path, sep=r"\s+", header=None, names=['Group','Module','Channel','Tap',
        'Pressure[Pa]'])
    configuration_map = pd.read_csv(configuration_map_path, sep=';')

    # --- Concatenates the pressure data to the configuration map ---
    scan_data = configuration_map.join(scan_data['Pressure[Pa]'])

    # --- Saves the reference pressure values ---
    p_tot = scan_data.loc[scan_data['Tap-ID'] == 'P_tot', 'Pressure[Pa]'].iloc[0]
    p_inf = scan_data.loc[scan_data['Tap-ID'] == 'P_inf', 'Pressure[Pa]'].iloc[0]
    p_din_uncorrected = p_tot - p_inf

    # --- Converts the relevant columns to numeric values ---
    scan_data['Tap-ID'] = pd.to_numeric(scan_data['Tap-ID'], errors='coerce')
    scan_data['x/c'] = pd.to_numeric(scan_data['x/c'], errors='coerce')
    scan_data['y/b'] = pd.to_numeric(scan_data['y/b'], errors='coerce')

    # --- Drops unused taps ---
    scan_data = scan_data.dropna(subset=['Tap-ID'])

    # --- Filters the scan data for a specific section and reorders by tap ID ---
    section_id = section_number * 100
    scan_data = scan_data[(scan_data['Tap-ID']>=(section_id)) & (scan_data['Tap-ID']<(section_id+100))]
    scan_data = scan_data.sort_values(by=['Tap-ID']).reset_index(drop=True)

    # --- Corrects the dynamic pressure considering the blockage factor ---
    epsilon = calculate_blockage_correction(AoA_uncorrected)
    p_din_corrected = p_din_uncorrected * ((1 + epsilon)**2)

    # --- Concatenates the correction factor, the dynamic pressure and the pressure coefficient data ---
    scan_data['Epsilon'] = epsilon
    scan_data['P_din_uncorrected'] = p_din_uncorrected
    scan_data['P_din'] = p_din_corrected
    scan_data['Cp'] = (scan_data['Pressure[Pa]'] - p_inf) / p_din_corrected

    # --- Reshapes the scan data into a single row ---
    scan_data = pd.DataFrame([[scan_data['y/b'].iloc[0], scan_data['P_din_uncorrected'].iloc[0],
        scan_data['P_din'].iloc[0], scan_data['Epsilon'].iloc[0], *scan_data['Cp'].values]],
        columns=['y/b', 'P_din_uncorrected', 'P_din', 'Epsilon', 
        *[str(float(v)) for v in (scan_data['Tap-ID'] - section_id).values]])
                                            
    return scan_data

def process_polar_data(complete_aerodynamic_data_path: str, fuselage_aerodynamic_data_path: str, 
    configuration_map_path: str):
    """
    Process one experimental dataset partition from wind tunnel measurements. 

    This function combines aerodynamic balance data and pressure scan data for all operating conditions
    of a selected sensor configuration. It applies blockage corrections, reconstructs pressure 
    distributions, computes aerodynamic coefficients, and assembles the processed dataset.

    The output corresponds to a partial dataset that must be merged with other configurations to form
    the complete experimental database.

    Parameters
    ----------
    complete_aerodynamic_data_path : str
        Path to the complete aerodynamic polar file.

    fuselage_aerodynamic_data_path : str
        Path to the fuselage-only aerodynamic polar file used for interference correction.

    configuration_map_path : str
        Path to the sensor mapping file defining pressure tap locations.

    Returns
    -------
    pressure_data : pandas.DataFrame
        Processed parcial dataset containing corrected operating conditions and pressure coefficient
        distributions. 
    """

    # --- Loads the aerodynamic data for saving the uncorrected Re value ---
    Re_uncorrected = pd.read_csv(complete_aerodynamic_data_path, sep=r"\s+")
    Re_uncorrected = float(Re_uncorrected.iloc[0, 6])

    # --- Loads the aerodynamic data and saves the uncorrected AoA, lift and drag values ---
    aerodynamic_data = pd.read_csv(complete_aerodynamic_data_path, sep=r"\s+", skiprows=3, 
        usecols=[0, 2, 3], names=['AoA_uncorrected[deg]', 'L[V]', 'D[V]'])
    fuselage_data = pd.read_csv(fuselage_aerodynamic_data_path, sep=r"\s+", skiprows=3, 
        usecols=[2, 3], names=['L[V]', 'D[V]'])
    
    # --- Subtracts the fuselage lift and drag contributions ---
    aerodynamic_data['L[V]'] = aerodynamic_data['L[V]'] - fuselage_data['L[V]']
    aerodynamic_data['D[V]'] = aerodynamic_data['D[V]'] - fuselage_data['D[V]']

    # --- Converts the aerodynamic forces from volts to newtons using the calibration factors ---
    aerodynamic_data['L[N]'] = aerodynamic_data['L[V]']*14.9773
    aerodynamic_data['D[N]'] = aerodynamic_data['D[V]']*10.84836

    # --- Defines the final final assembled dataset columns and rows---
    assembled_columns = ['AoA_uncorrected[deg]', 'L[N]', 'D[N]', 'CL_uncorrected', 'y/b', 'P_din', 
        'Epsilon', 'L[V]', 'D[V]', 'P_din_uncorrected', '1.0', '2.0', '3.0', '4.0', '5.0', '6.0', '7.0', 
        '8.0', '9.0', '10.0', '11.0',  '12.0', '13.0', '14.0', '15.0', '16.0', '17.0', '18.0', '19.0', 
        '20.0', '21.0', '22.0', '23.0', '24.0', '25.0', '26.0', '27.0', '28.0', '29.0', '30.0', '31.0']
    assembled_rows = []

    # --- Loops through the 21 scan data files ---
    for i in range(21):
        scan_path = f'experimental-input/SCAN{i:03d}.dat'

        # --- Processes the scan data for the Alpha configuration ---
        if configuration_map_path == 'sensor-mappings/Alpha_Mapping.csv':
            # Processes the scan data for the sections 7 and 8:
            scan_data_section_7 = process_scan_data(scan_path, configuration_map_path, 7, 
                aerodynamic_data['AoA_uncorrected[deg]'][i]) 
            scan_data_section_8 = process_scan_data(scan_path, configuration_map_path, 8, 
                aerodynamic_data['AoA_uncorrected[deg]'][i])

            # Concatenates the scan data with the aerodynamic data:
            pressure_data_section_7 = pd.concat([aerodynamic_data.iloc[[i]].reset_index(drop=True), 
                scan_data_section_7.iloc[[0]].reset_index(drop=True)], axis=1).reindex(columns=assembled_columns)
            pressure_data_section_8 = pd.concat([aerodynamic_data.iloc[[i]].reset_index(drop=True), 
                scan_data_section_8.iloc[[0]].reset_index(drop=True)], axis=1).reindex(columns=assembled_columns)

            # Appends the scan data to the assembled dataset:
            assembled_rows.extend([pressure_data_section_7, pressure_data_section_8])


        # --- Processes the scan data for the Bravo configuration ---
        elif configuration_map_path == 'sensor-mappings/Bravo_Mapping.csv':
            # Processes the scan data for the sections 5 and 6:
            scan_data_section_5 = process_scan_data(scan_path, configuration_map_path, 5, 
                aerodynamic_data['AoA_uncorrected[deg]'][i]) 
            scan_data_section_6 = process_scan_data(scan_path, configuration_map_path, 6, 
                aerodynamic_data['AoA_uncorrected[deg]'][i])

            # Concatenates the scan data with the aerodynamic data:
            pressure_data_section_5 = pd.concat([aerodynamic_data.iloc[[i]].reset_index(drop=True), 
                scan_data_section_5.iloc[[0]].reset_index(drop=True)], axis=1).reindex(columns=assembled_columns)
            pressure_data_section_6 = pd.concat([aerodynamic_data.iloc[[i]].reset_index(drop=True), 
                scan_data_section_6.iloc[[0]].reset_index(drop=True)], axis=1).reindex(columns=assembled_columns)

            # Appends the scan data to the assembled dataset:
            assembled_rows.extend([pressure_data_section_5, pressure_data_section_6])

        
        # --- Processes the scan data for the Charlie configuration ---
        elif configuration_map_path == 'sensor-mappings/Charlie_Mapping.csv':
            # Processes the scan data for the sections 2 and 3:
            scan_data_section_2 = process_scan_data(scan_path, configuration_map_path, 2, 
                aerodynamic_data['AoA_uncorrected[deg]'][i]) 
            scan_data_section_3 = process_scan_data(scan_path, configuration_map_path, 3, 
                aerodynamic_data['AoA_uncorrected[deg]'][i])

            # Concatenates the scan data with the aerodynamic data:
            pressure_data_section_2 = pd.concat([aerodynamic_data.iloc[[i]].reset_index(drop=True), 
                scan_data_section_2.iloc[[0]].reset_index(drop=True)], axis=1).reindex(columns=assembled_columns)
            pressure_data_section_3 = pd.concat([aerodynamic_data.iloc[[i]].reset_index(drop=True), 
                scan_data_section_3.iloc[[0]].reset_index(drop=True)], axis=1).reindex(columns=assembled_columns)

            # Appends the scan data to the assembled dataset:
            assembled_rows.extend([pressure_data_section_2, pressure_data_section_3])


        # --- Processes the scan data for the Delta configuration ---
        elif configuration_map_path == 'sensor-mappings/Delta_Mapping.csv':
            # Processes the scan data for the sections 7 and 8:
            scan_data_section_4 = process_scan_data(scan_path, configuration_map_path, 4, 
                aerodynamic_data['AoA_uncorrected[deg]'][i]) 

            # Concatenates the scan data with the aerodynamic data:
            pressure_data_section_4 = pd.concat([aerodynamic_data.iloc[[i]].reset_index(drop=True), 
                scan_data_section_4.iloc[[0]].reset_index(drop=True)], axis=1).reindex(columns=assembled_columns)

            # Appends the scan data to the assembled dataset:
            assembled_rows.extend([pressure_data_section_4])
            

    # --- Concatenates the scan data for all angle of attacks ---
    pressure_data = pd.concat(assembled_rows, ignore_index=True, sort=False)

    # --- Applies the Reynolds number correction and appends to the dataset ---
    mean_epsilon = np.mean(pressure_data['Epsilon'])
    Re_corrected = Re_uncorrected * (1 + mean_epsilon)
    pressure_data.insert(0, 'Re', int(Re_corrected))

    # --- Calculates the uncorrected lift coefficient ---
    pressure_data['CL_uncorrected'] = pressure_data['L[N]']/(pressure_data['P_din_uncorrected']
        *(0.766 * 0.2165))

    # --- Calculates the corrected wing lift coefficient (CL) ---
    pressure_data['CL'] = (pressure_data['L[N]'])/(pressure_data['P_din']*(0.766 * 0.2165))

    # --- Calculates the semicorrected wing drag coefficient (CD) ---
    pressure_data['CD_semicorrected'] = (pressure_data['D[N]'])/(pressure_data['P_din']*(0.766 * 0.2165))

    # --- Applies the corrected wing lift coefficient for the angle of attack and drag correction ---
    delta = 0.125
    pressure_data['dAoA[deg]'] = 57.3 * delta * ((2 * 0.766 * 0.2165)/(1.3 * 1.7)) * pressure_data['CL']
    pressure_data['dCD'] = (delta * ((2 * 0.766 * 0.2165)/(1.3 * 1.7)) * pressure_data['CL_uncorrected']* 
        pressure_data['CL_uncorrected'])

    # Applies the correction to the angle of attack and to the drag:
    pressure_data['AoA[deg]'] = pressure_data['AoA_uncorrected[deg]'] + pressure_data['dAoA[deg]']
    pressure_data['CD'] = pressure_data['CD_semicorrected'] + pressure_data['dCD']

    # Adds the physical angle of attack offset to the data:
    AoA_offset = 4.4794
    pressure_data.insert(1, 'AoA', pressure_data['AoA[deg]'] + AoA_offset)

    # --- Cleans the dataset from unnecessary columns ---
    pressure_data = pressure_data.drop(columns=['AoA_uncorrected[deg]', 'L[N]', 'D[N]', 'CL_uncorrected',
        'CD_semicorrected', 'dCD', 'Epsilon', 'dAoA[deg]', 'AoA[deg]', 'P_din', 'L[V]', 'D[V]', 
        'P_din_uncorrected'])

    # --- Fills the missing points with a linear interpolation ---
    cp_columns = sorted([c for c in pressure_data.columns if c not in ['Re', 'AoA', 'y/b', 'CL', 'CD']], 
        key=float)
    pressure_data[cp_columns] = (pressure_data[cp_columns].astype(float).interpolate(axis=1, 
        method='linear', limit_direction='both'))

    # --- Reorders the columns before renamning ---
    pressure_data = pressure_data[['Re', 'AoA', 'y/b', 'CL', 'CD'] + cp_columns]

    # --- Renames the pressure coefficient columns based on their chordwise position ---
    chordwise_pos = np.array([0.91685912, 0.82101617, 0.72623557, 0.63353349, 0.5439261, 0.45842956, 
        0.37792148, 0.30337182, 0.23551963, 0.17510393, 0.12281755, 0.07926097, 0.04489607, 0.02004619, 
        0.00503464, 0, 0.00503464, 0.02004619, 0.04489607, 0.07926097, 0.12281755, 0.17510393, 0.23551963, 
        0.30337182, 0.37792148, 0.45842956, 0.5439261, 0.63353349, 0.72623557, 0.82101617, 0.91685912])
    pressure_data.columns = ['Re', 'AoA', 'y', 'CL', 'CD'] + list(np.round(chordwise_pos, 5))

    return pressure_data

def plot_polar_data(pressure_data: pd.DataFrame):
    """
    Generate visual inspection plots for all processed pressure distributions.

    This function creates one plot per row of the processed dataset showing the pressure coefficient
    distribution along the airfoil chord. The figures are intended for quality control and manual
    inspection before the final dataset assembly stage.

    Parameters
    ----------
    pressure_data : pd.DataFrame
        Processed partial dataset containing pressure coefficient distributions.

    Returns
    -------
    None
        The generated figures are saved to disk.
    """

    # --- Defines the x positions for the pressure coefficient data ---
    x_position = pressure_data.columns[5:].astype(float).to_numpy()

    # --- Plots the pressure coefficient data for each row of the dataset ---
    for i, (_, row) in enumerate(pressure_data.iterrows(), start=1):
        cp = row.iloc[5:].astype(float).values

        # Setting plot parameters:
        with plt.rc_context({'font.family': 'serif', 'font.serif': ['Times New Roman'],
            'mathtext.fontset': 'stix'}):

            # --- Figure size: single-column ---
            fig, ax = plt.subplots(figsize=(3.35, 2.55))

            # --- Plot ---
            plot = ax.plot(x_position, cp, marker='s', linestyle='--', markersize=1, linewidth=0.2, 
                color='k')

            # --- Labels ---
            ax.set_xlabel('x/c', fontsize=8, fontname='Times New Roman', labelpad=5)
            ax.set_ylabel(r'$C_p$', fontsize=8, fontname='Times New Roman', labelpad=5)
            Re, AoA, yb  = row.iloc[0], row.iloc[1], row.iloc[2]
            ax.set_title(f'Re = {Re:.0f} | AoA = {AoA:.2f} | y/b = {yb:.3f}', fontsize=10, 
                fontname='Times New Roman')

            # --- Ticks ---
            for spine in ax.spines.values():
                spine.set_linewidth(0.5)
            ax.tick_params(axis='both', which='major', labelsize=6, width=0.4, direction='in')
            ax.xaxis.set_major_locator(MaxNLocator(6))
            ax.yaxis.set_major_locator(MaxNLocator(6))
            ax.invert_yaxis()

            # --- Grid ---
            ax.grid(True, which='both', linestyle='--', linewidth=0.5, alpha=0.2)

            # --- Limits ---
            ax.set_xlim(-0.05, 1.05)
            ax.set_ylim(1.1, -4)

            # --- Save plot ---
            plt.tight_layout(pad=0.6)
            plt.savefig(f'visual-checks/check_{i:03d}.png', dpi=300)
            plt.close()

    return

def main(complete_aerodynamic_data_path: str, fuselage_aerodynamic_data_path: str, 
    configuration_map_path: str):
    """
    Process one experimental dataset partition from wind tunnel measurements.

    This function combines aerodynamic balance data and pressure scan data for all operating conditions 
    of a selected sensor configuration. It applies blockage corrections, reconstructs pressure 
    distributions, computes aerodynamic coefficients, and assembles the processed dataset.

    The output corresponds to a partial dataset that must be merged with other configurations to form the 
    complete experimental database.

    Parameters
    ----------
    complete_aerodynamic_data_path : str
        Path to the complete aerodynamic polar file.

    fuselage_aerodynamic_data_path : str
        Path to the fuselage-only aerodynamic polar file used for interference correction.

    configuration_map_path : str
        Path to the sensor mapping file defining pressure tap locations.

    Returns
    -------
    pressure_data : pandas.DataFrame
        Processed partial dataset containing corrected operating conditions and pressure coefficient 
        distributions.
    """

    # --- Processes the pressure coefficient data ---
    print('\nStarting data processing pipeline...\n')
    pressure_data = process_polar_data(complete_aerodynamic_data_path, fuselage_aerodynamic_data_path, 
        configuration_map_path)

    # --- Saves the pressure coefficient data ---
    pressure_data.to_csv(f'pipeline-output/{Path(complete_aerodynamic_data_path).stem}.csv', index=False)
    print(f'Saved: "pipeline-output/{Path(complete_aerodynamic_data_path).stem}.csv".\n')

    # --- Cleans the visual checks folder ---
    for file in Path('visual-checks').glob('*.png'):
        file.unlink()

    # --- Plots the pressure coefficient data ---
    plot_polar_data(pressure_data)
    print('Visual checks successfully saved at "visual-checks" folder.\n')
    
    return

if __name__ == '__main__':
    main(complete_aerodynamic_data_path, fuselage_aerodynamic_data_path, configuration_map_path)