# -*- coding: utf-8 -*-
"""
========================================================================================================
Module: potential_data_checker
Author: Caio Dias Filho
Creation date: 2026-02-20
Last modification: 2026-02-21
Version: 1.0
========================================================================================================

OVERVIEW
--------
This module validates the aerodynamic dataset generated by 'potential_data_generator.py'.

The objective is to:

    1) Recompute sectional lift coefficients (Cl) by integrating Cp.
    2) Compare computed Cl with dataset reference values.
    3) Quantify absolute error.
    4) Identify observations exceeding a physically defined tolerance.
    5) Generate a structured validation report.
    6) Remove inconsistent observations.


VALIDATION RATIONALE
--------------------
The absolute error verification is primarily used as a convergence detector for XFoil sectional analyses.
Large discrepancies between the dataset and the Cp-integrated Cl are interpreted as a potential XFoil non-
converged solutions. Therefore, observations exceeding the defined tolerance are treated as numerically
inconsistent cases rather than physically extreme conditions. The tolerance is defined based on manual
observations in which the XFoil fails to converge, and the detected cases are manually evaluated before
being excluded from the dataset.


DEPENDENCIES
------------
Python libraries:
    - tqdm
    - pandas
    - numpy
    - time

    
OUTPUT FILES
------------
- data_checker_report.txt
- Potential-PressureDistributionData.csv


NOTES
-----
- Only Cp contribution is considered in Cl integration.
- The tolerance must be physically justified.
- This script does NOT recompute stall filtering.

========================================================================================================
"""

# =======================================================================================================
#                                            USER INPUT SECTION
# =======================================================================================================

# --- Validation parameters ---
# Physical tolerance for |ΔCl|:
tolerance = 0.01


# =======================================================================================================
#                                              CORE FUNCTION
# =======================================================================================================

from tqdm import tqdm
import pandas as pd
import numpy as np
import time

def compute_cl_from_cp(cp_data:np.ndarray, airfoil_data:pd.DataFrame, AoA:float):
    """
    Recompute the sectional lift coefficient (Cl) by integrating the pressure coefficient (Cp).

    This function performs a numerical integration of the discrete Cp distribution over the airfoil surface
    to obtain the normal (Cn) and axial (Ca) force coefficients. These are subsequently projected using the
    Angle of Attack (AoA) to calculate the lift coefficient (Cl).

    Parameters
    ----------
    cp_data : np.ndarray
        Array containing the 201 chordwise pressure coefficient values.

    airfoil_data : pd.DataFrame
        DataFrame containing the gometry of the airfoil with columns ['x', 'y'].

    AoA : float 
        Angle of attack [degrees] of the current sectional case.

    Returns
    -------
    calc_cl : float
        The calculated sectional lift coefficient integrated from the Cp distribution.

    Notes
    -----
    - Integration assumes a standard trapezoidal-like approximation based on panel deltas.
    - Skin friction contribution is ignored; only pressure forces are integrated.
    """

    # 1. Calculte panel geometric deltas (dx, dy):
    panel_dx = np.diff(airfoil_data['x'].values)
    panel_dy = np.diff(airfoil_data['y'].values)

    # 2. Compute the average Cp for each panel:
    panel_cp = (cp_data[:-1] + cp_data[1:])/2

    # 3. Integrate to find normal (Cn) and axial (Ca) force coefficients:
    airfoil_cn = np.sum(panel_cp * panel_dx)
    airfoil_ca = -np.sum(panel_cp * panel_dy)

    # 4. Project Cn and Ca into the lift coefficient (Cl) using the angle of attack:
    calc_cl = airfoil_cn * np.cos(np.radians(AoA)) - airfoil_ca * np.sin(np.radians(AoA))

    return calc_cl

def evaluate_absolute_error(dataset:pd.DataFrame, airfoil_data:pd.DataFrame):
    """
    Evaluate the absolute error between the dataset Cl and the Cp-integrated Cl for all cases.

    Iterates through the entire aerodynamic dataset, recomputing the lift coefficient for each
    observations and calculating the absolute difference against the reference Cl generated by XFoil.

    Parameters
    ----------
    dataset : pd.DataFrame
        The generated potential dataset containing Re, AoA, y, cl, and the 201 Cp values.

    airfoil_data : pd.DataFrame
        DataFrame containing the geometry of the airfoil.

    Returns
    -------
    results_df : pd.DataFrame
        DataFrame containing the validation metrics for each case:
            - Re : Reynolds number
            - AoA : Angle of attack [degrees]
            - y : Normalized spanwise position
            - cl : Original reference lift coefficient
            - absolute_error : Absolute difference between original and integrated Cl
    """

    # 1. Initialize the results list:
    results = []
    
    # 2. Iterate through all the observations in the dataset to compute errors:
    for i in tqdm(range(len(dataset)), desc="Evaluating Cl absolute error...", unit="case"):
        # Extract paramaters for the current case:
        cp_values = dataset.iloc[i, 4:].values
        Re = dataset.iloc[i, 0]
        AoA = dataset.iloc[i, 1]
        y = dataset.iloc[i, 2]
        true_cl = dataset.iloc[i, 3]

        # Recompute Cl and calculate the absolute error:
        calc_cl = compute_cl_from_cp(cp_values, airfoil_data, AoA)
        abs_error = np.abs(true_cl - calc_cl)

        results.append([Re, AoA, y, true_cl, abs_error])

    # 3. Assemble and return the results DataFrame:
    results_df = pd.DataFrame(results, columns=['Re', 'AoA', 'y', 'cl', 'absolute_error'])

    return results_df

def generate_error_report(results:pd.DataFrame, tolerance:float):
    """
    Generate a formatted text report of the validation results and identify problematic cases.

    This function filters the results to find observations where the absolute error exceeds the predefined
    physical tolerance, compiling these cases into a readable text report.

    Parameters
    ----------
    results : pd.DataFrame
        DataFrame containing validation metrics (Re, AoA, y, cl, absolute_error) for all cases.

    tolerance : float
        Maximum acceptable absolute difference between reference Cl and integrated Cl.

    Returns
    -------
    errors.index : pd.Index
        The dataset indices of the observations that exceeded the defined tolerance.

    Side Effects
    ------------
    - Writes a structured text report to 'potential_error_report.txt'.
    """

    # 1. Filter observations that exceed the defined tolerance:
    errors = results[results['absolute_error'] > tolerance]

    # 2. Compute global error statistics:
    n_errors = len(errors)
    total = len(results)
    percentage = 100 * n_errors / total

    # 3. Assemble the report header and statistics:
    content = f"""ABSOLUTE ERROR ANALYSIS REPORT - Cl CALCULATION
===========================================================
Date: {time.strftime("%Y-%m-%d %H:%M:%S")}

1. GLOBAL ERROR STATISTICS
----------------------------------
Tolerance adopted: {tolerance:.2f}.
Total observations: {total}.
Observations above tolerance: {n_errors}.
Percentage above tolerance: {percentage:.2f}%.

2. OBSERVATIONS ABOVE TOLERANCE
----------------------------------
"""

    # 4. Append detailed information for each problematic observation:
    if n_errors > 0:
        detailed = "\n".join([
            f"Re={row.Re:<10.0f} | AoA={row.AoA:<6.0f} | y={row.y:<8.4f} | "
            f"Cl={row.cl:<10.4f} | AbsError={row.absolute_error:.6f}"
            for _, row in errors.iterrows()])
        content += detailed
    else:
        content += "No observations exceeded the defined tolerance."
    content += "\n===========================================================\n"

    # 5. Write the report to disk:
    with open('potential_error_report.txt', "w", encoding="utf-8") as f:
        f.write(content)

    print(f"\nValidation report saved to: 'potential_error_report.txt'.\n")

    return errors.index

def main():
    """
    Execute the complete aerodynamic dataset validation workflow.

    This function coordinates the complete pipeline:
        1. Load the generated dataset and the reference airfoil geometry.
        2. Compute absolute_errors for Cl using Cp integration.
        3. Generate a structured validation report and extract inconsistent indices.
        4. Remove inconsistent observations from the dataset.
        5. Export the clean, filtered dataset to disk.

    Returns
    -------
    None
        This function saves the final filtered dataset and report to disk.

    Output
    ------
    'potential_error_report.txt'
        Text file detailing observations that failed to converge (exceeded tolerance).
        
    'Potential-PressureDistributionData.csv'
        The final cleaned dataset with inconsistent XFoil results removed.
    """

    print('\nStarting dataset validation...\n')

    # 1. Load dataset and reference airfoil geometry:
    dataset = pd.read_csv('Potential-PressureDistributionData.csv', sep=';')
    airfoil_data = pd.read_csv('utils/NACA23015.csv', sep=',', names=['x','y'])

    # 2. Remove NaN observations generate by XFoil unconverged cases, if any are present:
    initial_len = len(dataset)
    dataset = dataset.dropna().reset_index(drop=True)
    nan_removed = initial_len - len(dataset)
    if nan_removed > 0:
        print(f"Removed {nan_removed} NaN observations (missing XFoil output) before analysis.\n")

    # 3. Compute absolute errors:
    results = evaluate_absolute_error(dataset, airfoil_data)

    # 4. Generate validation report and get indices to remove:
    indices_to_remove = generate_error_report(results, tolerance)

    # 5. Remove inconsistent observations based on tolerance:
    filtered_dataset = dataset.drop(index=indices_to_remove)

    # 6. Print the final validation results:
    print(f'Original dataset size (without NaNs): {len(dataset)} observations.')
    print(f'Observations identified as non-converged (above tolerance): {len(indices_to_remove)} observations.')
    print(f'Observations physically consistent (below tolerance): {len(filtered_dataset)} observations.')

    # 7. Save the filtered dataset:
    filtered_dataset.to_csv('Potential-PressureDistributionData-Filtered.csv', index=False, sep=';')

    print("\nFiltered dataset saved to: 'Potential-PressureDistributionData_filtered.csv'.\n")
    print('Dataset validation completed successfully!\n')
    
    return

if __name__ == "__main__":
    main()